{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9.1 Teste: sazonalidade anual com Fourier (variante, não substitui o 9.0)\n",
    "\n",
    "**Ideia:** Fourier são ondas de seno/cosseno com período de 1 ano. Com k=1,2,3 o modelo consegue desenhar uma curva anual suave (ex: 'novembro costuma ser mais alto').\n",
    "\n",
    "**Regra de ouro:** as colunas precisam ser calculadas **igual** no treino e no futuro (mesma `EPOCA`, mesmo período 365.25). Se uma for diferente, a onda 'desalinha' e a previsão sai errada.\n",
    "\n",
    "**Como decidir:** backtest só do SARIMA 2023 com Fourier vs o resultado atual (sem Fourier). Só entra em produção se o erro cair de forma consistente."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9.1.1 Colunas de Fourier no calendário FUTURO (jul a set/2026)\n",
    "\n",
    "EPOCA = pd.Timestamp(\"2020-01-01\")   # mesma data usada no teste anterior\n",
    "PERIODO_ANUAL = 365.25\n",
    "K_FOURIER = 3\n",
    "\n",
    "COLS_FOURIER = []\n",
    "for k in range(1, K_FOURIER + 1):\n",
    "    COLS_FOURIER += [f\"fourier_sin_{k}\", f\"fourier_cos_{k}\"]\n",
    "\n",
    "COLS_EXOG_FOURIER = COLS_EXOG + COLS_FOURIER\n",
    "\n",
    "t_futuro = (exog_futuro[\"dt_movimento\"] - EPOCA).dt.days\n",
    "for k in range(1, K_FOURIER + 1):\n",
    "    exog_futuro[f\"fourier_sin_{k}\"] = np.sin(2 * np.pi * k * t_futuro / PERIODO_ANUAL)\n",
    "    exog_futuro[f\"fourier_cos_{k}\"] = np.cos(2 * np.pi * k * t_futuro / PERIODO_ANUAL)\n",
    "\n",
    "print(\"Colunas usadas na variante Fourier:\", COLS_EXOG_FOURIER)\n",
    "exog_futuro[[\"dt_movimento\"] + COLS_FOURIER].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9.1.2 Colunas de Fourier no TREINO — Prime\n",
    "\n",
    "t_prime = (df_prime[\"dt_movimento\"] - EPOCA).dt.days\n",
    "for k in range(1, K_FOURIER + 1):\n",
    "    df_prime[f\"fourier_sin_{k}\"] = np.sin(2 * np.pi * k * t_prime / PERIODO_ANUAL)\n",
    "    df_prime[f\"fourier_cos_{k}\"] = np.cos(2 * np.pi * k * t_prime / PERIODO_ANUAL)\n",
    "\n",
    "df_prime[[\"dt_movimento\"] + COLS_FOURIER].tail()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9.1.3 Colunas de Fourier no TREINO — Varejo\n",
    "\n",
    "t_varejo = (df_varejo[\"dt_movimento\"] - EPOCA).dt.days\n",
    "for k in range(1, K_FOURIER + 1):\n",
    "    df_varejo[f\"fourier_sin_{k}\"] = np.sin(2 * np.pi * k * t_varejo / PERIODO_ANUAL)\n",
    "    df_varejo[f\"fourier_cos_{k}\"] = np.cos(2 * np.pi * k * t_varejo / PERIODO_ANUAL)\n",
    "\n",
    "df_varejo[[\"dt_movimento\"] + COLS_FOURIER].tail()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9.1.4 Backtest do teste — Prime (SARIMA, janela 2023, COM Fourier)\n",
    "# Mesmas origens, gap e horizonte do 8.0. Só muda a lista de colunas exógenas.\n",
    "\n",
    "resultados_prime_fourier = []\n",
    "\n",
    "for origem_pos in origens_prime:\n",
    "    origem_data = df_prime.loc[origem_pos, \"dt_movimento\"]\n",
    "    teste = df_prime.iloc[origem_pos + GAP_UTEIS + 1 : origem_pos + GAP_UTEIS + HORIZONTE_UTEIS + 1]\n",
    "    real = teste[\"qt_venda\"].values\n",
    "\n",
    "    treino = df_prime[(df_prime[\"dt_movimento\"] >= \"2023-01-01\") & (df_prime.index <= origem_pos)]\n",
    "\n",
    "    modelo = auto_arima(treino[\"qt_venda\"], X=treino[COLS_EXOG_FOURIER], d=D_POR_JANELA[(\"prime\", \"2023\")],\n",
    "                        seasonal=False, suppress_warnings=True, error_action=\"ignore\", stepwise=True)\n",
    "\n",
    "    exog_bloco = df_prime.iloc[origem_pos + 1 : origem_pos + BLOCO_UTEIS + 1][COLS_EXOG_FOURIER]\n",
    "    previsto = np.array(modelo.predict(n_periods=BLOCO_UTEIS, X=exog_bloco))[-HORIZONTE_UTEIS:]\n",
    "\n",
    "    resultados_prime_fourier.append({\"origem\": origem_data.date(),\n",
    "                                     \"mape\": np.mean(np.abs((real - previsto) / real)) * 100,\n",
    "                                     \"rmse\": np.sqrt(np.mean((real - previsto) ** 2)),\n",
    "                                     \"mae\": np.mean(np.abs(real - previsto))})\n",
    "    print(\"origem\", origem_data.date(), \"concluída\")\n",
    "\n",
    "df_res_prime_fourier = pd.DataFrame(resultados_prime_fourier)\n",
    "\n",
    "print(\"\\nPRIME — SARIMA 2023 (média das origens)\")\n",
    "print(\"SEM Fourier:\", resumo_prime.loc[(\"2023\", \"sarima\")].to_dict())\n",
    "print(\"COM Fourier:\", df_res_prime_fourier[[\"mape\", \"rmse\", \"mae\"]].mean().round(2).to_dict())\n",
    "df_res_prime_fourier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9.1.5 Backtest do teste — Varejo (SARIMA, janela 2023, COM Fourier)\n",
    "\n",
    "resultados_varejo_fourier = []\n",
    "\n",
    "for origem_pos in origens_varejo:\n",
    "    origem_data = df_varejo.loc[origem_pos, \"dt_movimento\"]\n",
    "    teste = df_varejo.iloc[origem_pos + GAP_UTEIS + 1 : origem_pos + GAP_UTEIS + HORIZONTE_UTEIS + 1]\n",
    "    real = teste[\"qt_venda\"].values\n",
    "\n",
    "    treino = df_varejo[(df_varejo[\"dt_movimento\"] >= \"2023-01-01\") & (df_varejo.index <= origem_pos)]\n",
    "\n",
    "    modelo = auto_arima(treino[\"qt_venda\"], X=treino[COLS_EXOG_FOURIER], d=D_POR_JANELA[(\"varejo\", \"2023\")],\n",
    "                        seasonal=False, suppress_warnings=True, error_action=\"ignore\", stepwise=True)\n",
    "\n",
    "    exog_bloco = df_varejo.iloc[origem_pos + 1 : origem_pos + BLOCO_UTEIS + 1][COLS_EXOG_FOURIER]\n",
    "    previsto = np.array(modelo.predict(n_periods=BLOCO_UTEIS, X=exog_bloco))[-HORIZONTE_UTEIS:]\n",
    "\n",
    "    resultados_varejo_fourier.append({\"origem\": origem_data.date(),\n",
    "                                      \"mape\": np.mean(np.abs((real - previsto) / real)) * 100,\n",
    "                                      \"rmse\": np.sqrt(np.mean((real - previsto) ** 2)),\n",
    "                                      \"mae\": np.mean(np.abs(real - previsto))})\n",
    "    print(\"origem\", origem_data.date(), \"concluída\")\n",
    "\n",
    "df_res_varejo_fourier = pd.DataFrame(resultados_varejo_fourier)\n",
    "\n",
    "print(\"\\nVAREJO — SARIMA 2023 (média das origens)\")\n",
    "print(\"SEM Fourier:\", resumo_varejo.loc[(\"2023\", \"sarima\")].to_dict())\n",
    "print(\"COM Fourier:\", df_res_varejo_fourier[[\"mape\", \"rmse\", \"mae\"]].mean().round(2).to_dict())\n",
    "df_res_varejo_fourier"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9.1.6 Modelo final COM Fourier — Prime (variante; o 9.0 original fica intacto)\n",
    "\n",
    "treino_final_prime_f = df_prime[df_prime[\"dt_movimento\"] >= \"2023-01-01\"].reset_index(drop=True)\n",
    "\n",
    "modelo_final_prime_f = auto_arima(treino_final_prime_f[\"qt_venda\"], X=treino_final_prime_f[COLS_EXOG_FOURIER],\n",
    "                                  d=D_POR_JANELA[(\"prime\", \"2023\")], seasonal=False,\n",
    "                                  suppress_warnings=True, error_action=\"ignore\", stepwise=True)\n",
    "\n",
    "previsto_prime_f, ic_prime_f = modelo_final_prime_f.predict(n_periods=len(exog_futuro),\n",
    "                                                           X=exog_futuro[COLS_EXOG_FOURIER],\n",
    "                                                           return_conf_int=True, alpha=0.05)\n",
    "\n",
    "resultado_prime_fourier = pd.DataFrame({\n",
    "    \"dt_movimento\": exog_futuro[\"dt_movimento\"].reset_index(drop=True),\n",
    "    \"previsto\": np.asarray(previsto_prime_f),\n",
    "    \"limite_inferior_95\": np.asarray(ic_prime_f)[:, 0],\n",
    "    \"limite_superior_95\": np.asarray(ic_prime_f)[:, 1],\n",
    "})\n",
    "resultado_prime_fourier_setembro = resultado_prime_fourier[resultado_prime_fourier[\"dt_movimento\"] >= \"2026-09-01\"].reset_index(drop=True)\n",
    "resultado_prime_fourier_setembro"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9.1.7 Modelo final COM Fourier — Varejo\n",
    "\n",
    "treino_final_varejo_f = df_varejo[df_varejo[\"dt_movimento\"] >= \"2023-01-01\"].reset_index(drop=True)\n",
    "\n",
    "modelo_final_varejo_f = auto_arima(treino_final_varejo_f[\"qt_venda\"], X=treino_final_varejo_f[COLS_EXOG_FOURIER],\n",
    "                                   d=D_POR_JANELA[(\"varejo\", \"2023\")], seasonal=False,\n",
    "                                   suppress_warnings=True, error_action=\"ignore\", stepwise=True)\n",
    "\n",
    "previsto_varejo_f, ic_varejo_f = modelo_final_varejo_f.predict(n_periods=len(exog_futuro),\n",
    "                                                              X=exog_futuro[COLS_EXOG_FOURIER],\n",
    "                                                              return_conf_int=True, alpha=0.05)\n",
    "\n",
    "resultado_varejo_fourier = pd.DataFrame({\n",
    "    \"dt_movimento\": exog_futuro[\"dt_movimento\"].reset_index(drop=True),\n",
    "    \"previsto\": np.asarray(previsto_varejo_f),\n",
    "    \"limite_inferior_95\": np.asarray(ic_varejo_f)[:, 0],\n",
    "    \"limite_superior_95\": np.asarray(ic_varejo_f)[:, 1],\n",
    "})\n",
    "resultado_varejo_fourier_setembro = resultado_varejo_fourier[resultado_varejo_fourier[\"dt_movimento\"] >= \"2026-09-01\"].reset_index(drop=True)\n",
    "resultado_varejo_fourier_setembro"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9.1.8 Comparação visual: baseline (sem Fourier) vs Fourier — setembro/2026\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "fig, eixos = plt.subplots(1, 2, figsize=(16, 5))\n",
    "\n",
    "eixos[0].plot(resultado_prime_setembro[\"dt_movimento\"], resultado_prime_setembro[\"previsto\"], marker=\"o\", label=\"Sem Fourier (atual)\")\n",
    "eixos[0].plot(resultado_prime_fourier_setembro[\"dt_movimento\"], resultado_prime_fourier_setembro[\"previsto\"], marker=\"s\", label=\"Com Fourier\")\n",
    "eixos[0].set_title(\"Prime — previsão de setembro\")\n",
    "eixos[0].legend()\n",
    "eixos[0].tick_params(axis=\"x\", rotation=45)\n",
    "\n",
    "eixos[1].plot(resultado_varejo_setembro[\"dt_movimento\"], resultado_varejo_setembro[\"previsto\"], marker=\"o\", label=\"Sem Fourier (atual)\")\n",
    "eixos[1].plot(resultado_varejo_fourier_setembro[\"dt_movimento\"], resultado_varejo_fourier_setembro[\"previsto\"], marker=\"s\", label=\"Com Fourier\")\n",
    "eixos[1].set_title(\"Varejo — previsão de setembro\")\n",
    "eixos[1].legend()\n",
    "eixos[1].tick_params(axis=\"x\", rotation=45)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# diferença média entre as duas versões (em %)\n",
    "dif_prime = (resultado_prime_fourier_setembro[\"previsto\"] / resultado_prime_setembro[\"previsto\"] - 1).mean() * 100\n",
    "dif_varejo = (resultado_varejo_fourier_setembro[\"previsto\"] / resultado_varejo_setembro[\"previsto\"] - 1).mean() * 100\n",
    "print(f\"Diferença média Fourier vs atual — Prime: {dif_prime:.1f}% | Varejo: {dif_varejo:.1f}%\")"
   ]
  }
 ]
}
