{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ccff24a3",
   "metadata": {},
   "source": [
    "## 8.0 Backtest — como funciona\n",
    "\n",
    "### A ideia central\n",
    "\n",
    "Não dá pra simplesmente testar o modelo prevendo dias que ele já viu no treino — isso não prova nada (ele decorou). O backtest simula uma previsão de verdade: escondo um pedaço do futuro do modelo, peço a previsão, e só depois comparo com o que realmente aconteceu.\n",
    "\n",
    "Cada rodada desse teste (um **bloco**) tem três partes, na ordem em que aparecem no tempo:\n",
    "\n",
    "```\n",
    "|<---------- TREINO ---------->|<---- GAP (44 du) ---->|<--- HORIZONTE (21 du) --->|\n",
    "      o modelo aprende aqui         ele NÃO vê nada aqui      ele PREVÊ aqui, e é isso\n",
    "                                                                que comparamos com o real\n",
    "   ↑                          ↑\n",
    "início da janela          ORIGEM\n",
    "(ex: 2024-01-01)      (data de corte do treino)\n",
    "```\n",
    "\n",
    "O gap de **44 dias úteis** e o horizonte de **21 dias úteis** não são arbitrários — são exatamente o tamanho de julho+agosto (o buraco real) e de setembro (o mês que queremos prever). Um gap menor testaria um problema mais fácil que o real, e o backtest enganaria a gente.\n",
    "\n",
    "### \"Expanding window\" — por que o treino cresce\n",
    "\n",
    "Dentro de uma mesma janela (ex: \"desde 2024\"), o **início do treino fica fixo**, e só a origem (fim do treino) avança. Cada bloco novo tem mais dado de treino que o anterior — o modelo só ganha histórico, nunca perde:\n",
    "\n",
    "```\n",
    "Janela \"desde 2024\" — o início (2024-01) nunca muda, só a origem anda pra frente:\n",
    "\n",
    "origem 1:  [2024-01 ---- treino ---- 2024-07]···gap···|horizonte|\n",
    "origem 2:  [2024-01 -------- treino -------- 2024-11]···gap···|horizonte|\n",
    "origem 3:  [2024-01 ------------ treino ------------ 2025-03]···gap···|horizonte|\n",
    "origem 4:  [2024-01 ---------------- treino ---------------- 2025-07]···gap···|horizonte|\n",
    "```\n",
    "\n",
    "### Vários blocos, sem se sobrepor\n",
    "\n",
    "Uma única origem seria um \"teste de sorte\". Por isso repito o processo em **~6 pontos diferentes da história**, espaçados pra um bloco nunca invadir o outro:\n",
    "\n",
    "```\n",
    "2024-07 ────┬[treino]├─gap─┤horiz├\n",
    "2024-11 ─────────┬[treino]├─gap─┤horiz├\n",
    "2025-03 ──────────────┬[treino]├─gap─┤horiz├\n",
    "2025-07 ───────────────────┬[treino]├─gap─┤horiz├\n",
    "2025-11 ────────────────────────┬[treino]├─gap─┤horiz├\n",
    "2026-03 ─────────────────────────────┬[treino]├─gap─┤horiz├  ← última origem (limite: 30/06/2026)\n",
    "```\n",
    "\n",
    "E as **mesmas 6 origens valem para as 3 janelas** (completo, desde 2023, desde 2024) — assim, ao comparar o erro entre janelas, a única coisa que muda é quanto histórico o modelo viu, não em que período ele foi testado.\n",
    "\n",
    "### O que sai de cada bloco\n",
    "\n",
    "Em cada origem, treino Prophet e SARIMA, peço a previsão dos 21 dias do horizonte, e calculo o erro (MAPE, RMSE, MAE) comparando previsto × real:\n",
    "\n",
    "```\n",
    "origem × janela × modelo  ->  1 conjunto de erros (MAPE, RMSE, MAE)\n",
    "\n",
    "6 origens x 3 janelas x 2 modelos x 2 segmentos = 72 \"provas\" no total\n",
    "```\n",
    "\n",
    "No final, tiro a **média dos erros dos 6 blocos** para cada combinação (janela, modelo) — essa média decide o vencedor. Um modelo que só acerta num bloco e erra feio nos outros 5 não passa: é exatamente esse tipo de sorte/azar isolado que rodar vários blocos evita.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "92d525dc",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Backtest — parâmetros fixos, iguais ao cenário real (treino até 30/06, setembro é o alvo)\n",
    "\n",
    "from pmdarima import auto_arima  # pip install pmdarima, se ainda não tiver\n",
    "\n",
    "GAP_UTEIS = 44        # jul + ago/2026: dias úteis que ficam \"no escuro\" entre o treino e a previsão\n",
    "HORIZONTE_UTEIS = 21  # setembro/2026: dias úteis, já descontando o feriado de 7/9\n",
    "BLOCO_UTEIS = GAP_UTEIS + HORIZONTE_UTEIS  # 65 -> espaçamento entre origens, pra blocos não se sobreporem\n",
    "\n",
    "INICIO_MINIMO = pd.Timestamp(\"2024-07-01\")  # ~6 meses de treino mínimo pra janela \"desde 2024\" na 1ª origem\n",
    "\n",
    "JANELAS_INICIO = {\"2020\": \"2020-01-01\", \"2023\": \"2023-01-01\", \"2024\": \"2024-01-01\"}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "39c7de70",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Origens do backtest — Prime\n",
    "# Anda de trás pra frente a partir da última origem possível, em passos de BLOCO_UTEIS\n",
    "# (65 dias úteis), até chegar perto do início mínimo. As mesmas origens valem pras 3 janelas.\n",
    "\n",
    "pos_minima_prime = df_prime[df_prime[\"dt_movimento\"] >= INICIO_MINIMO].index.min()\n",
    "pos_maxima_origem_prime = len(df_prime) - 1 - BLOCO_UTEIS\n",
    "\n",
    "origens_prime = []\n",
    "pos = pos_maxima_origem_prime\n",
    "while pos >= pos_minima_prime:\n",
    "    origens_prime.append(pos)\n",
    "    pos -= BLOCO_UTEIS\n",
    "origens_prime = sorted(origens_prime)\n",
    "\n",
    "print(\"Prime — origens do backtest:\")\n",
    "for pos in origens_prime:\n",
    "    print(pos, \"->\", df_prime.loc[pos, \"dt_movimento\"].date())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88045f5e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Origens do backtest — Varejo\n",
    "\n",
    "pos_minima_varejo = df_varejo[df_varejo[\"dt_movimento\"] >= INICIO_MINIMO].index.min()\n",
    "pos_maxima_origem_varejo = len(df_varejo) - 1 - BLOCO_UTEIS\n",
    "\n",
    "origens_varejo = []\n",
    "pos = pos_maxima_origem_varejo\n",
    "while pos >= pos_minima_varejo:\n",
    "    origens_varejo.append(pos)\n",
    "    pos -= BLOCO_UTEIS\n",
    "origens_varejo = sorted(origens_varejo)\n",
    "\n",
    "print(\"Varejo — origens do backtest:\")\n",
    "for pos in origens_varejo:\n",
    "    print(pos, \"->\", df_varejo.loc[pos, \"dt_movimento\"].date())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d326914",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Execução do backtest — Prime\n",
    "# Pra cada origem x janela: treina Prophet e SARIMA, prevê os 21 dias de teste (depois do\n",
    "# gap de 44), e mede MAPE/RMSE/MAE. O SARIMA usa auto_arima pra escolher p e q sozinho\n",
    "# (com base no AIC) — o d já está travado pelo Dickey-Fuller, sem seasonal (já sabemos\n",
    "# que s=7 não funciona numa série só de dia útil). Pode demorar alguns minutos.\n",
    "\n",
    "resultados_prime = []\n",
    "\n",
    "for origem_pos in origens_prime:\n",
    "    origem_data = df_prime.loc[origem_pos, \"dt_movimento\"]\n",
    "    teste = df_prime.iloc[origem_pos + GAP_UTEIS + 1 : origem_pos + GAP_UTEIS + HORIZONTE_UTEIS + 1]\n",
    "    real = teste[\"qt_venda\"].values\n",
    "\n",
    "    for janela, inicio_janela in JANELAS_INICIO.items():\n",
    "        treino = df_prime[(df_prime[\"dt_movimento\"] >= inicio_janela) & (df_prime.index <= origem_pos)]\n",
    "\n",
    "        # --- Prophet ---\n",
    "        treino_prophet = treino[[\"dt_movimento\", \"qt_venda\"] + REGRESSORES_PROPHET].rename(\n",
    "            columns={\"dt_movimento\": \"ds\", \"qt_venda\": \"y\"})\n",
    "\n",
    "        modelo_prophet = Prophet(weekly_seasonality=True, yearly_seasonality=False, daily_seasonality=False)\n",
    "        for col in REGRESSORES_PROPHET:\n",
    "            modelo_prophet.add_regressor(col)\n",
    "        modelo_prophet.fit(treino_prophet)\n",
    "\n",
    "        futuro_prophet = teste[[\"dt_movimento\"] + REGRESSORES_PROPHET].rename(columns={\"dt_movimento\": \"ds\"})\n",
    "        previsto_prophet = modelo_prophet.predict(futuro_prophet)[\"yhat\"].values\n",
    "\n",
    "        mape_prophet = np.mean(np.abs((real - previsto_prophet) / real)) * 100\n",
    "        rmse_prophet = np.sqrt(np.mean((real - previsto_prophet) ** 2))\n",
    "        mae_prophet = np.mean(np.abs(real - previsto_prophet))\n",
    "\n",
    "        resultados_prime.append({\"origem\": origem_data.date(), \"janela\": janela, \"modelo\": \"prophet\",\n",
    "                                  \"mape\": mape_prophet, \"rmse\": rmse_prophet, \"mae\": mae_prophet})\n",
    "\n",
    "        # --- SARIMA ---\n",
    "        treino_y = treino[\"qt_venda\"]\n",
    "        treino_exog = treino[COLS_EXOG]\n",
    "        d_janela = D_POR_JANELA[(\"prime\", janela)]\n",
    "\n",
    "        modelo_sarima = auto_arima(treino_y, X=treino_exog, d=d_janela, seasonal=False,\n",
    "                                    suppress_warnings=True, error_action=\"ignore\", stepwise=True)\n",
    "\n",
    "        exog_futuro = df_prime.iloc[origem_pos + 1 : origem_pos + BLOCO_UTEIS + 1][COLS_EXOG]\n",
    "        previsto_sarima_completo = modelo_sarima.predict(n_periods=BLOCO_UTEIS, X=exog_futuro)\n",
    "        previsto_sarima = np.array(previsto_sarima_completo)[-HORIZONTE_UTEIS:]\n",
    "\n",
    "        mape_sarima = np.mean(np.abs((real - previsto_sarima) / real)) * 100\n",
    "        rmse_sarima = np.sqrt(np.mean((real - previsto_sarima) ** 2))\n",
    "        mae_sarima = np.mean(np.abs(real - previsto_sarima))\n",
    "\n",
    "        resultados_prime.append({\"origem\": origem_data.date(), \"janela\": janela, \"modelo\": \"sarima\",\n",
    "                                  \"mape\": mape_sarima, \"rmse\": rmse_sarima, \"mae\": mae_sarima})\n",
    "\n",
    "    print(\"origem\", origem_data.date(), \"concluída\")\n",
    "\n",
    "df_resultados_prime = pd.DataFrame(resultados_prime)\n",
    "df_resultados_prime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc8c31a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Execução do backtest — Varejo (mesma lógica, trocando prime -> varejo)\n",
    "\n",
    "resultados_varejo = []\n",
    "\n",
    "for origem_pos in origens_varejo:\n",
    "    origem_data = df_varejo.loc[origem_pos, \"dt_movimento\"]\n",
    "    teste = df_varejo.iloc[origem_pos + GAP_UTEIS + 1 : origem_pos + GAP_UTEIS + HORIZONTE_UTEIS + 1]\n",
    "    real = teste[\"qt_venda\"].values\n",
    "\n",
    "    for janela, inicio_janela in JANELAS_INICIO.items():\n",
    "        treino = df_varejo[(df_varejo[\"dt_movimento\"] >= inicio_janela) & (df_varejo.index <= origem_pos)]\n",
    "\n",
    "        # --- Prophet ---\n",
    "        treino_prophet = treino[[\"dt_movimento\", \"qt_venda\"] + REGRESSORES_PROPHET].rename(\n",
    "            columns={\"dt_movimento\": \"ds\", \"qt_venda\": \"y\"})\n",
    "\n",
    "        modelo_prophet = Prophet(weekly_seasonality=True, yearly_seasonality=False, daily_seasonality=False)\n",
    "        for col in REGRESSORES_PROPHET:\n",
    "            modelo_prophet.add_regressor(col)\n",
    "        modelo_prophet.fit(treino_prophet)\n",
    "\n",
    "        futuro_prophet = teste[[\"dt_movimento\"] + REGRESSORES_PROPHET].rename(columns={\"dt_movimento\": \"ds\"})\n",
    "        previsto_prophet = modelo_prophet.predict(futuro_prophet)[\"yhat\"].values\n",
    "\n",
    "        mape_prophet = np.mean(np.abs((real - previsto_prophet) / real)) * 100\n",
    "        rmse_prophet = np.sqrt(np.mean((real - previsto_prophet) ** 2))\n",
    "        mae_prophet = np.mean(np.abs(real - previsto_prophet))\n",
    "\n",
    "        resultados_varejo.append({\"origem\": origem_data.date(), \"janela\": janela, \"modelo\": \"prophet\",\n",
    "                                   \"mape\": mape_prophet, \"rmse\": rmse_prophet, \"mae\": mae_prophet})\n",
    "\n",
    "        # --- SARIMA ---\n",
    "        treino_y = treino[\"qt_venda\"]\n",
    "        treino_exog = treino[COLS_EXOG]\n",
    "        d_janela = D_POR_JANELA[(\"varejo\", janela)]\n",
    "\n",
    "        modelo_sarima = auto_arima(treino_y, X=treino_exog, d=d_janela, seasonal=False,\n",
    "                                    suppress_warnings=True, error_action=\"ignore\", stepwise=True)\n",
    "\n",
    "        exog_futuro = df_varejo.iloc[origem_pos + 1 : origem_pos + BLOCO_UTEIS + 1][COLS_EXOG]\n",
    "        previsto_sarima_completo = modelo_sarima.predict(n_periods=BLOCO_UTEIS, X=exog_futuro)\n",
    "        previsto_sarima = np.array(previsto_sarima_completo)[-HORIZONTE_UTEIS:]\n",
    "\n",
    "        mape_sarima = np.mean(np.abs((real - previsto_sarima) / real)) * 100\n",
    "        rmse_sarima = np.sqrt(np.mean((real - previsto_sarima) ** 2))\n",
    "        mae_sarima = np.mean(np.abs(real - previsto_sarima))\n",
    "\n",
    "        resultados_varejo.append({\"origem\": origem_data.date(), \"janela\": janela, \"modelo\": \"sarima\",\n",
    "                                   \"mape\": mape_sarima, \"rmse\": rmse_sarima, \"mae\": mae_sarima})\n",
    "\n",
    "    print(\"origem\", origem_data.date(), \"concluída\")\n",
    "\n",
    "df_resultados_varejo = pd.DataFrame(resultados_varejo)\n",
    "df_resultados_varejo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "14a9a186",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Resumo — média das métricas por janela x modelo (isso é o que decide o vencedor)\n",
    "\n",
    "resumo_prime = df_resultados_prime.groupby([\"janela\", \"modelo\"])[[\"mape\", \"rmse\", \"mae\"]].mean().round(2)\n",
    "print(\"PRIME\")\n",
    "print(resumo_prime)\n",
    "\n",
    "resumo_varejo = df_resultados_varejo.groupby([\"janela\", \"modelo\"])[[\"mape\", \"rmse\", \"mae\"]].mean().round(2)\n",
    "print(\"\\nVAREJO\")\n",
    "print(resumo_varejo)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
