{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c02124c7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Backtest — parâmetros fixos, iguais ao cenário real (treino até 30/06, setembro é o alvo)\n",
    "\n",
    "from pmdarima import auto_arima  # pip install pmdarima, se ainda não tiver\n",
    "\n",
    "GAP_UTEIS = 44        # jul + ago/2026: dias úteis que ficam \"no escuro\" entre o treino e a previsão\n",
    "HORIZONTE_UTEIS = 21  # setembro/2026: dias úteis, já descontando o feriado de 7/9\n",
    "BLOCO_UTEIS = GAP_UTEIS + HORIZONTE_UTEIS  # 65 -> espaçamento entre origens, pra blocos não se sobreporem\n",
    "\n",
    "INICIO_MINIMO = pd.Timestamp(\"2024-07-01\")  # ~6 meses de treino mínimo pra janela \"desde 2024\" na 1ª origem\n",
    "\n",
    "JANELAS_INICIO = {\"2020\": \"2020-01-01\", \"2023\": \"2023-01-01\", \"2024\": \"2024-01-01\"}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "af28230c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Origens do backtest — Prime\n",
    "# Anda de trás pra frente a partir da última origem possível, em passos de BLOCO_UTEIS\n",
    "# (65 dias úteis), até chegar perto do início mínimo. As mesmas origens valem pras 3 janelas.\n",
    "\n",
    "pos_minima_prime = df_prime[df_prime[\"dt_movimento\"] >= INICIO_MINIMO].index.min()\n",
    "pos_maxima_origem_prime = len(df_prime) - 1 - BLOCO_UTEIS\n",
    "\n",
    "origens_prime = []\n",
    "pos = pos_maxima_origem_prime\n",
    "while pos >= pos_minima_prime:\n",
    "    origens_prime.append(pos)\n",
    "    pos -= BLOCO_UTEIS\n",
    "origens_prime = sorted(origens_prime)\n",
    "\n",
    "print(\"Prime — origens do backtest:\")\n",
    "for pos in origens_prime:\n",
    "    print(pos, \"->\", df_prime.loc[pos, \"dt_movimento\"].date())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4bf25b75",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Origens do backtest — Varejo\n",
    "\n",
    "pos_minima_varejo = df_varejo[df_varejo[\"dt_movimento\"] >= INICIO_MINIMO].index.min()\n",
    "pos_maxima_origem_varejo = len(df_varejo) - 1 - BLOCO_UTEIS\n",
    "\n",
    "origens_varejo = []\n",
    "pos = pos_maxima_origem_varejo\n",
    "while pos >= pos_minima_varejo:\n",
    "    origens_varejo.append(pos)\n",
    "    pos -= BLOCO_UTEIS\n",
    "origens_varejo = sorted(origens_varejo)\n",
    "\n",
    "print(\"Varejo — origens do backtest:\")\n",
    "for pos in origens_varejo:\n",
    "    print(pos, \"->\", df_varejo.loc[pos, \"dt_movimento\"].date())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78e2a45f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Execução do backtest — Prime\n",
    "# Pra cada origem x janela: treina Prophet e SARIMA, prevê os 21 dias de teste (depois do\n",
    "# gap de 44), e mede MAPE/RMSE/MAE. O SARIMA usa auto_arima pra escolher p e q sozinho\n",
    "# (com base no AIC) — o d já está travado pelo Dickey-Fuller, sem seasonal (já sabemos\n",
    "# que s=7 não funciona numa série só de dia útil). Pode demorar alguns minutos.\n",
    "\n",
    "resultados_prime = []\n",
    "\n",
    "for origem_pos in origens_prime:\n",
    "    origem_data = df_prime.loc[origem_pos, \"dt_movimento\"]\n",
    "    teste = df_prime.iloc[origem_pos + GAP_UTEIS + 1 : origem_pos + GAP_UTEIS + HORIZONTE_UTEIS + 1]\n",
    "    real = teste[\"qt_venda\"].values\n",
    "\n",
    "    for janela, inicio_janela in JANELAS_INICIO.items():\n",
    "        treino = df_prime[(df_prime[\"dt_movimento\"] >= inicio_janela) & (df_prime.index <= origem_pos)]\n",
    "\n",
    "        # --- Prophet ---\n",
    "        treino_prophet = treino[[\"dt_movimento\", \"qt_venda\"] + REGRESSORES_PROPHET].rename(\n",
    "            columns={\"dt_movimento\": \"ds\", \"qt_venda\": \"y\"})\n",
    "\n",
    "        modelo_prophet = Prophet(weekly_seasonality=True, yearly_seasonality=False, daily_seasonality=False)\n",
    "        for col in REGRESSORES_PROPHET:\n",
    "            modelo_prophet.add_regressor(col)\n",
    "        modelo_prophet.fit(treino_prophet)\n",
    "\n",
    "        futuro_prophet = teste[[\"dt_movimento\"] + REGRESSORES_PROPHET].rename(columns={\"dt_movimento\": \"ds\"})\n",
    "        previsto_prophet = modelo_prophet.predict(futuro_prophet)[\"yhat\"].values\n",
    "\n",
    "        mape_prophet = np.mean(np.abs((real - previsto_prophet) / real)) * 100\n",
    "        rmse_prophet = np.sqrt(np.mean((real - previsto_prophet) ** 2))\n",
    "        mae_prophet = np.mean(np.abs(real - previsto_prophet))\n",
    "\n",
    "        resultados_prime.append({\"origem\": origem_data.date(), \"janela\": janela, \"modelo\": \"prophet\",\n",
    "                                  \"mape\": mape_prophet, \"rmse\": rmse_prophet, \"mae\": mae_prophet})\n",
    "\n",
    "        # --- SARIMA ---\n",
    "        treino_y = treino[\"qt_venda\"]\n",
    "        treino_exog = treino[COLS_EXOG]\n",
    "        d_janela = D_POR_JANELA[(\"prime\", janela)]\n",
    "\n",
    "        modelo_sarima = auto_arima(treino_y, X=treino_exog, d=d_janela, seasonal=False,\n",
    "                                    suppress_warnings=True, error_action=\"ignore\", stepwise=True)\n",
    "\n",
    "        exog_futuro = df_prime.iloc[origem_pos + 1 : origem_pos + BLOCO_UTEIS + 1][COLS_EXOG]\n",
    "        previsto_sarima_completo = modelo_sarima.predict(n_periods=BLOCO_UTEIS, X=exog_futuro)\n",
    "        previsto_sarima = np.array(previsto_sarima_completo)[-HORIZONTE_UTEIS:]\n",
    "\n",
    "        mape_sarima = np.mean(np.abs((real - previsto_sarima) / real)) * 100\n",
    "        rmse_sarima = np.sqrt(np.mean((real - previsto_sarima) ** 2))\n",
    "        mae_sarima = np.mean(np.abs(real - previsto_sarima))\n",
    "\n",
    "        resultados_prime.append({\"origem\": origem_data.date(), \"janela\": janela, \"modelo\": \"sarima\",\n",
    "                                  \"mape\": mape_sarima, \"rmse\": rmse_sarima, \"mae\": mae_sarima})\n",
    "\n",
    "    print(\"origem\", origem_data.date(), \"concluída\")\n",
    "\n",
    "df_resultados_prime = pd.DataFrame(resultados_prime)\n",
    "df_resultados_prime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9a54e3ce",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Execução do backtest — Varejo (mesma lógica, trocando prime -> varejo)\n",
    "\n",
    "resultados_varejo = []\n",
    "\n",
    "for origem_pos in origens_varejo:\n",
    "    origem_data = df_varejo.loc[origem_pos, \"dt_movimento\"]\n",
    "    teste = df_varejo.iloc[origem_pos + GAP_UTEIS + 1 : origem_pos + GAP_UTEIS + HORIZONTE_UTEIS + 1]\n",
    "    real = teste[\"qt_venda\"].values\n",
    "\n",
    "    for janela, inicio_janela in JANELAS_INICIO.items():\n",
    "        treino = df_varejo[(df_varejo[\"dt_movimento\"] >= inicio_janela) & (df_varejo.index <= origem_pos)]\n",
    "\n",
    "        # --- Prophet ---\n",
    "        treino_prophet = treino[[\"dt_movimento\", \"qt_venda\"] + REGRESSORES_PROPHET].rename(\n",
    "            columns={\"dt_movimento\": \"ds\", \"qt_venda\": \"y\"})\n",
    "\n",
    "        modelo_prophet = Prophet(weekly_seasonality=True, yearly_seasonality=False, daily_seasonality=False)\n",
    "        for col in REGRESSORES_PROPHET:\n",
    "            modelo_prophet.add_regressor(col)\n",
    "        modelo_prophet.fit(treino_prophet)\n",
    "\n",
    "        futuro_prophet = teste[[\"dt_movimento\"] + REGRESSORES_PROPHET].rename(columns={\"dt_movimento\": \"ds\"})\n",
    "        previsto_prophet = modelo_prophet.predict(futuro_prophet)[\"yhat\"].values\n",
    "\n",
    "        mape_prophet = np.mean(np.abs((real - previsto_prophet) / real)) * 100\n",
    "        rmse_prophet = np.sqrt(np.mean((real - previsto_prophet) ** 2))\n",
    "        mae_prophet = np.mean(np.abs(real - previsto_prophet))\n",
    "\n",
    "        resultados_varejo.append({\"origem\": origem_data.date(), \"janela\": janela, \"modelo\": \"prophet\",\n",
    "                                   \"mape\": mape_prophet, \"rmse\": rmse_prophet, \"mae\": mae_prophet})\n",
    "\n",
    "        # --- SARIMA ---\n",
    "        treino_y = treino[\"qt_venda\"]\n",
    "        treino_exog = treino[COLS_EXOG]\n",
    "        d_janela = D_POR_JANELA[(\"varejo\", janela)]\n",
    "\n",
    "        modelo_sarima = auto_arima(treino_y, X=treino_exog, d=d_janela, seasonal=False,\n",
    "                                    suppress_warnings=True, error_action=\"ignore\", stepwise=True)\n",
    "\n",
    "        exog_futuro = df_varejo.iloc[origem_pos + 1 : origem_pos + BLOCO_UTEIS + 1][COLS_EXOG]\n",
    "        previsto_sarima_completo = modelo_sarima.predict(n_periods=BLOCO_UTEIS, X=exog_futuro)\n",
    "        previsto_sarima = np.array(previsto_sarima_completo)[-HORIZONTE_UTEIS:]\n",
    "\n",
    "        mape_sarima = np.mean(np.abs((real - previsto_sarima) / real)) * 100\n",
    "        rmse_sarima = np.sqrt(np.mean((real - previsto_sarima) ** 2))\n",
    "        mae_sarima = np.mean(np.abs(real - previsto_sarima))\n",
    "\n",
    "        resultados_varejo.append({\"origem\": origem_data.date(), \"janela\": janela, \"modelo\": \"sarima\",\n",
    "                                   \"mape\": mape_sarima, \"rmse\": rmse_sarima, \"mae\": mae_sarima})\n",
    "\n",
    "    print(\"origem\", origem_data.date(), \"concluída\")\n",
    "\n",
    "df_resultados_varejo = pd.DataFrame(resultados_varejo)\n",
    "df_resultados_varejo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "312fa8b1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Resumo — média das métricas por janela x modelo (isso é o que decide o vencedor)\n",
    "\n",
    "resumo_prime = df_resultados_prime.groupby([\"janela\", \"modelo\"])[[\"mape\", \"rmse\", \"mae\"]].mean().round(2)\n",
    "print(\"PRIME\")\n",
    "print(resumo_prime)\n",
    "\n",
    "resumo_varejo = df_resultados_varejo.groupby([\"janela\", \"modelo\"])[[\"mape\", \"rmse\", \"mae\"]].mean().round(2)\n",
    "print(\"\\nVAREJO\")\n",
    "print(resumo_varejo)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
